### ISSUE TITLE
package definition xcode 

### ISSUE THREAD

**Issue by madamc** [STREGAsGate/Raylib#5]
I was able to get this running in xcode 13.1, but I had to modify the package file slightly.

I had to modify the package and target thusly:

`
.package(name: "Raylib", url: "https://github.com/STREGAsGate/Raylib.git", .branch("master"))	

...
       .target(
            name: "<project name>",
            dependencies: ["Raylib"]),
`

without this, I would receive the error "No such module 'Raylib'" when I tried to import "Raylib" in my swift files. Not sure if it's an update with newer versions of Swift or not.

This is a fantastic project. Thanks for putting this work together.

**Comment by STREGAsGate** [comment]
Yes, this is a known restriction in Swift's package manager. 
I've added a note about this to the readme to help users avoid this pitfall.
Raylib will continue to get tags in the hopes that someday the SwiftPM restriction will be removed, but users must use master until then.
See this issue https://github.com/STREGAsGate/Raylib/issues/6
