### ISSUE TITLE
Please indicate that `.branch("master")` is necessary to avoid a build error regarding unsafe build flags for Raylib and GLFW

### ISSUE THREAD

**Issue by willowell** [STREGAsGate/Raylib#6]
Hello! Thank you very much for creating this Swift package to streamline working with Raylib.

While testing out your library, I tried using `from: "4.0.0"` for the package and encountered this error:

```
error: the target '_RaylibC' in product 'Raylib' contains unsafe build flags
```

Then I discovered this thread regarding the use of `.unsafeFlags()` and `.branch()` / `from` - https://forums.swift.org/t/question-about-contains-unsafe-build-flags-in-spm/47677

I understand that since your library needs to use `.unsafeFlags()` to compile Raylib and GLFW together via `clang -x objective-c -fno-obj-arc`, could you please document that users of this library must use `.branch("master")`?

**Comment by STREGAsGate** [comment]
I've added a note to the readme regarding this issue.
https://github.com/STREGAsGate/Raylib/commit/3ef6e4451ae9d1195daed526dc41ef0907f868ab
